import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { Copy, Check, RefreshCw, Save, Share2, Download, Sparkles } from 'lucide-react';
import { GeneratedDoc } from '../types';
import { refineDocument } from '../services/geminiService';

interface DocViewerProps {
  doc: GeneratedDoc;
  onUpdate: (newContent: string) => void;
}

const DocViewer: React.FC<DocViewerProps> = ({ doc, onUpdate }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [localContent, setLocalContent] = useState(doc.content);
  const [copied, setCopied] = useState(false);
  const [refinePrompt, setRefinePrompt] = useState('');
  const [isRefining, setIsRefining] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(localContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleRefine = async () => {
    if (!refinePrompt.trim()) return;
    setIsRefining(true);
    try {
      const refined = await refineDocument(localContent, refinePrompt);
      setLocalContent(refined);
      onUpdate(refined);
      setRefinePrompt('');
    } catch (e) {
      alert('Failed to refine document');
    } finally {
      setIsRefining(false);
    }
  };

  return (
    <div className="flex flex-col h-full gap-4 animate-in fade-in zoom-in-95 duration-300">
      {/* Toolbar */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 glass-panel rounded-xl border border-blue-500/20 shadow-lg shadow-blue-900/10">
        <div>
          <h2 className="text-xl font-bold text-white flex items-center gap-2">
            <span className="px-2 py-0.5 rounded bg-blue-500/20 text-blue-400 text-xs uppercase tracking-wide border border-blue-500/30">
              {doc.type}
            </span>
            {doc.title}
          </h2>
          <p className="text-xs text-slate-400 mt-1">Generated by ChatPRD Pro Agents</p>
        </div>
        <div className="flex items-center gap-2">
           <button 
            onClick={() => setIsEditing(!isEditing)}
            className="p-2 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition"
            title="Toggle Edit Mode"
          >
            {isEditing ? <Check className="w-5 h-5 text-green-400" /> : <span className="text-sm font-medium">Edit</span>}
          </button>
          <button 
            onClick={handleCopy}
            className="p-2 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition"
          >
            {copied ? <Check className="w-5 h-5 text-green-400" /> : <Copy className="w-5 h-5" />}
          </button>
          <button className="p-2 rounded-lg hover:bg-white/10 text-slate-400 hover:text-white transition">
            <Download className="w-5 h-5" />
          </button>
          <button className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white rounded-lg font-medium transition flex items-center gap-2 shadow-lg shadow-blue-500/20">
            <Share2 className="w-4 h-4" /> Share
          </button>
        </div>
      </div>

      {/* Main Content Area */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-3 gap-6 min-h-0">
        
        {/* Document Pane */}
        <div className="lg:col-span-2 glass-panel rounded-xl overflow-hidden flex flex-col border border-white/5">
           {isEditing ? (
             <textarea 
               className="flex-1 w-full h-full bg-slate-900/50 p-6 text-slate-300 font-mono text-sm resize-none focus:outline-none"
               value={localContent}
               onChange={(e) => setLocalContent(e.target.value)}
             />
           ) : (
            <div className="flex-1 overflow-y-auto p-8 markdown-body">
              <ReactMarkdown>{localContent}</ReactMarkdown>
            </div>
           )}
        </div>

        {/* AI Assistant Pane */}
        <div className="glass-panel rounded-xl p-4 flex flex-col gap-4 border border-white/5 h-fit sticky top-0">
          <div className="flex items-center gap-2 pb-2 border-b border-white/10">
            <Sparkles className="w-5 h-5 text-purple-400" />
            <h3 className="font-semibold text-white">AI Co-Pilot</h3>
          </div>
          
          <div className="flex-1 min-h-[200px] bg-black/20 rounded-lg p-4">
             <p className="text-sm text-slate-400 mb-4">
               I can rewrite sections, expand on technical details, or adjust the tone. What would you like to change?
             </p>
             <div className="space-y-3">
               <button onClick={() => setRefinePrompt("Make the tone more formal and enterprise-focused.")} className="w-full text-left text-xs text-blue-300 hover:text-blue-200 p-2 rounded hover:bg-blue-500/10 transition">✨ Make more formal</button>
               <button onClick={() => setRefinePrompt("Expand the Risk Assessment section.")} className="w-full text-left text-xs text-blue-300 hover:text-blue-200 p-2 rounded hover:bg-blue-500/10 transition">✨ Expand risks</button>
               <button onClick={() => setRefinePrompt("Convert the requirements list into a table.")} className="w-full text-left text-xs text-blue-300 hover:text-blue-200 p-2 rounded hover:bg-blue-500/10 transition">✨ Format as table</button>
             </div>
          </div>

          <div className="space-y-2">
            <textarea 
              value={refinePrompt}
              onChange={(e) => setRefinePrompt(e.target.value)}
              placeholder="Ask AI to refine..."
              className="w-full bg-black/30 border border-white/10 rounded-lg p-3 text-sm text-white focus:outline-none focus:border-purple-500 transition resize-none h-24"
            />
            <button 
              onClick={handleRefine}
              disabled={isRefining || !refinePrompt}
              className="w-full py-2 bg-gradient-to-r from-purple-600 to-blue-600 rounded-lg text-white font-medium hover:opacity-90 disabled:opacity-50 transition flex items-center justify-center gap-2"
            >
              {isRefining ? <RefreshCw className="w-4 h-4 animate-spin" /> : <Sparkles className="w-4 h-4" />}
              Refine Document
            </button>
          </div>
        </div>

      </div>
    </div>
  );
};

export default DocViewer;