import React from 'react';
import { Network, Download, Maximize2 } from 'lucide-react';

const Architecture = () => {
  return (
    <div className="space-y-8 animate-in fade-in duration-500">
       <div className="flex justify-between items-center">
        <div>
          <h1 className="text-3xl font-bold text-white">System Architecture</h1>
          <p className="text-slate-400">Visualizing system components and data flow.</p>
        </div>
         <div className="flex gap-3">
           <button className="px-4 py-2 border border-white/10 rounded-lg text-white text-sm font-medium hover:bg-white/5">
             Generate New
           </button>
           <button className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded-lg text-white text-sm font-medium flex items-center gap-2">
            <Download className="w-4 h-4" /> Export SVG
          </button>
         </div>
      </div>

      {/* Diagram Viewer Placeholder */}
      <div className="glass-panel rounded-xl border border-white/5 p-1 min-h-[600px] flex flex-col">
         <div className="bg-slate-950/50 flex-1 rounded-lg relative overflow-hidden flex items-center justify-center p-8">
            <div className="absolute inset-0 grid grid-cols-[repeat(20,minmax(0,1fr))] grid-rows-[repeat(20,minmax(0,1fr))] opacity-5">
              {Array.from({length: 400}).map((_, i) => (
                <div key={i} className="border-[0.5px] border-white"></div>
              ))}
            </div>

            {/* Mock Diagram for visual demo */}
            <div className="relative z-10 flex flex-col items-center gap-8 w-full max-w-3xl">
               
               {/* Client Layer */}
               <div className="flex gap-8">
                 <div className="w-32 h-20 rounded border-2 border-blue-500/50 bg-blue-900/20 flex flex-col items-center justify-center text-blue-300">
                    <span className="font-mono text-xs mb-1">Web Client</span>
                    <span className="text-[10px] opacity-50">React 18</span>
                 </div>
                  <div className="w-32 h-20 rounded border-2 border-blue-500/50 bg-blue-900/20 flex flex-col items-center justify-center text-blue-300">
                    <span className="font-mono text-xs mb-1">Mobile App</span>
                    <span className="text-[10px] opacity-50">React Native</span>
                 </div>
               </div>

               {/* Connection Lines */}
               <div className="h-12 w-0.5 bg-slate-600"></div>

               {/* API Gateway */}
               <div className="w-48 h-16 rounded border-2 border-purple-500/50 bg-purple-900/20 flex flex-col items-center justify-center text-purple-300 shadow-[0_0_15px_rgba(168,85,247,0.2)]">
                  <span className="font-mono text-sm font-bold">API Gateway</span>
                  <span className="text-[10px] opacity-50">Load Balancer / Auth</span>
               </div>

               {/* Connection Lines */}
               <div className="h-12 w-0.5 bg-slate-600"></div>

               {/* Microservices */}
               <div className="flex gap-4">
                  <div className="w-32 h-24 rounded border-2 border-emerald-500/50 bg-emerald-900/20 flex flex-col items-center justify-center text-emerald-300">
                    <span className="font-mono text-xs mb-1">Core Service</span>
                    <span className="text-[10px] opacity-50">Node.js</span>
                 </div>
                  <div className="w-32 h-24 rounded border-2 border-emerald-500/50 bg-emerald-900/20 flex flex-col items-center justify-center text-emerald-300">
                    <span className="font-mono text-xs mb-1">AI Engine</span>
                    <span className="text-[10px] opacity-50">Python / Gemini</span>
                 </div>
                  <div className="w-32 h-24 rounded border-2 border-emerald-500/50 bg-emerald-900/20 flex flex-col items-center justify-center text-emerald-300">
                    <span className="font-mono text-xs mb-1">Analytics</span>
                    <span className="text-[10px] opacity-50">Go</span>
                 </div>
               </div>

                {/* Connection Lines */}
               <div className="h-12 w-0.5 bg-slate-600"></div>

               {/* DB */}
               <div className="w-40 h-20 rounded-full border-2 border-orange-500/50 bg-orange-900/20 flex flex-col items-center justify-center text-orange-300 relative">
                  <div className="absolute top-1 w-32 h-4 rounded-full border border-orange-500/30"></div>
                  <span className="font-mono text-xs font-bold mt-2">PostgreSQL</span>
               </div>

            </div>
         </div>
         <div className="p-4 bg-slate-900 flex justify-between items-center text-xs text-slate-500">
           <span>Generated by Tech Agent</span>
           <button className="flex items-center gap-1 hover:text-white transition"><Maximize2 className="w-3 h-3" /> Full Screen</button>
         </div>
      </div>
    </div>
  );
};

export default Architecture;